#define SOMETHING = GET_TODAY()
#define ELSE = DATE_WITH_OFFSET("10-JAN-2020",3)
#define SOMETHING_ELSE = DATE_WITH_OFFSET(SOMETHING, 2)
Else is ELSE
Something is SOMETHING
Something else is SOMETHING_ELSE
