#define TODAY = GET_TODAY()
#define OFFSETED = DATE_WITH_OFFSET("10-JAN-2020",3)
#define TODAY_OFFSET = DATE_WITH_OFFSET(TODAY, 2)
#define DIFFERENCE = DIFFERENCE_IN_DAYS("10-JAN-2020",OFFSETED)
Today TODAY
Today offset TODAY_OFFSET
Offseted OFFSETED
Difference DIFFERENCE
